branch-defaults:
  master:
    environment: mhsalumdb
environment-defaults:
  mhsalumdb:
    branch: null
    repository: null
files:
  destinaiton: /var/www/html/
  source: null
global:
  application_name: MHSAlumDB
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v2.2.0 running PHP 7.0
  default_region: us-east-1
  profile: eb-cli
  sc: git
hooks:
  ApplicationStop:
  - location: scripts/stop_server
    runas: root
    timeout: 300
  BeforeInstall:
  - location: scripts/install_dependencies
    runas: root
    timeout: 300
  - location: scripts/start_server
    runas: root
    timeout: 300
os: linux
version: 0.2
